spring:
  datasource:
    url: jdbc:h2:mem:security-service
    username: admin
    password: admin
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
#      path: /db
      enabled: true