spring:
  banner:
    location: classpath:logo.ascii
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  data:
    mongodb:
      host: ${MONGODB_CRM_HOST}
      port: ${MONGODB_CRM_PORT}
      database: ${MONGODB_CRM_DATABASE}
      username: ${MONGODB_CRM_USERNAME}
      password: ${MONGODB_CRM_PASSWORD}


