spring:
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  file:
    path: ${LOG_PATH:logs}
